name: Veryfi-php main update

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: main-update
  cancel-in-progress: false

jobs:

  tests:

    runs-on: ${{ matrix.os }}

    strategy:

      fail-fast: false

      matrix:
        os:
          - ubuntu-latest

        php-version:
          - "8.3"

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name : Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: none

      - name: Install dependencies
        run: composer install --prefer-dist --ignore-platform-reqs

      - name: PHPUnit tests
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text --coverage-clover=report.xml

      - name: Generate Badges
        run: cd metrics && python ./generate_badges.py && cd ..

      - name: Publish Code Coverage Badges
        if: matrix.php-version == '8.3'
        run: ./.github/scripts/publish_badges.sh
